namespace BajajDocumentProcessing.Application.DTOs.Submissions;

/// <summary>
/// Enhanced validation report with detailed evidence and actionable recommendations
/// </summary>
public class EnhancedValidationReportDto
{
    /// <summary>
    /// Quick summary of validation results
    /// </summary>
    public ValidationSummaryDto Summary { get; set; } = new();

    /// <summary>
    /// Detailed validation results by category
    /// </summary>
    public List<ValidationCategoryDto> Categories { get; set; } = new();

    /// <summary>
    /// Confidence score breakdown by document type
    /// </summary>
    public ConfidenceBreakdownDto ConfidenceBreakdown { get; set; } = new();

    /// <summary>
    /// AI-generated recommendation with evidence
    /// </summary>
    public EnhancedRecommendationDto Recommendation { get; set; } = new();

    /// <summary>
    /// Detailed evidence narrative generated by AI
    /// </summary>
    public string DetailedEvidence { get; set; } = string.Empty;
}

/// <summary>
/// Quick summary of validation results
/// </summary>
public class ValidationSummaryDto
{
    /// <summary>
    /// Overall confidence score (0-100)
    /// </summary>
    public double OverallConfidence { get; set; }

    /// <summary>
    /// Total number of validation checks performed
    /// </summary>
    public int TotalValidations { get; set; }

    /// <summary>
    /// Number of validation checks that passed
    /// </summary>
    public int PassedValidations { get; set; }

    /// <summary>
    /// Number of validation checks that failed
    /// </summary>
    public int FailedValidations { get; set; }

    /// <summary>
    /// Number of critical issues found
    /// </summary>
    public int CriticalIssues { get; set; }

    /// <summary>
    /// Number of high priority issues found
    /// </summary>
    public int HighPriorityIssues { get; set; }

    /// <summary>
    /// Number of medium priority issues found
    /// </summary>
    public int MediumPriorityIssues { get; set; }

    /// <summary>
    /// Recommendation type: Approve, RequestResubmission, Reject
    /// </summary>
    public string RecommendationType { get; set; } = string.Empty;

    /// <summary>
    /// Risk level: Low, Medium, High
    /// </summary>
    public string RiskLevel { get; set; } = string.Empty;
}

/// <summary>
/// Validation category with pass/fail status and details
/// </summary>
public class ValidationCategoryDto
{
    /// <summary>
    /// Category name (e.g., "PO Number Cross-Validation")
    /// </summary>
    public string CategoryName { get; set; } = string.Empty;

    /// <summary>
    /// Icon name for UI display
    /// </summary>
    public string CategoryIcon { get; set; } = string.Empty;

    /// <summary>
    /// Whether this validation passed
    /// </summary>
    public bool Passed { get; set; }

    /// <summary>
    /// Status: Passed, Failed, Warning
    /// </summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>
    /// Severity: Critical, High, Medium, Low
    /// </summary>
    public string Severity { get; set; } = string.Empty;

    /// <summary>
    /// Short description for list view
    /// </summary>
    public string ShortDescription { get; set; } = string.Empty;

    /// <summary>
    /// Detailed information (null if passed without issues)
    /// </summary>
    public ValidationDetailDto? Details { get; set; }
}

/// <summary>
/// Detailed validation information for failed checks
/// </summary>
public class ValidationDetailDto
{
    /// <summary>
    /// Issue title
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Detailed description of the issue
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Expected value or condition
    /// </summary>
    public string ExpectedValue { get; set; } = string.Empty;

    /// <summary>
    /// Actual value found
    /// </summary>
    public string ActualValue { get; set; } = string.Empty;

    /// <summary>
    /// Impact of this issue on approval
    /// </summary>
    public string Impact { get; set; } = string.Empty;

    /// <summary>
    /// Suggested action to resolve
    /// </summary>
    public string SuggestedAction { get; set; } = string.Empty;

    /// <summary>
    /// List of affected documents
    /// </summary>
    public List<string> AffectedDocuments { get; set; } = new();

    /// <summary>
    /// Additional data for context
    /// </summary>
    public Dictionary<string, string> AdditionalData { get; set; } = new();
}

/// <summary>
/// Confidence score breakdown by document type
/// </summary>
public class ConfidenceBreakdownDto
{
    /// <summary>
    /// Overall weighted confidence score
    /// </summary>
    public double OverallConfidence { get; set; }

    /// <summary>
    /// PO document confidence
    /// </summary>
    public DocumentConfidenceDto POConfidence { get; set; } = new();

    /// <summary>
    /// Invoice document confidence
    /// </summary>
    public DocumentConfidenceDto InvoiceConfidence { get; set; } = new();

    /// <summary>
    /// Cost Summary document confidence
    /// </summary>
    public DocumentConfidenceDto CostSummaryConfidence { get; set; } = new();

    /// <summary>
    /// Activity document confidence
    /// </summary>
    public DocumentConfidenceDto ActivityConfidence { get; set; } = new();

    /// <summary>
    /// Photos confidence
    /// </summary>
    public DocumentConfidenceDto PhotosConfidence { get; set; } = new();
}

/// <summary>
/// Confidence score for a specific document type
/// </summary>
public class DocumentConfidenceDto
{
    /// <summary>
    /// Confidence score (0-100)
    /// </summary>
    public double Score { get; set; }

    /// <summary>
    /// Weight in overall calculation (0-1)
    /// </summary>
    public double Weight { get; set; }

    /// <summary>
    /// Number of validation checks that passed
    /// </summary>
    public int PassedChecks { get; set; }

    /// <summary>
    /// Total number of validation checks
    /// </summary>
    public int TotalChecks { get; set; }

    /// <summary>
    /// List of passed validation names
    /// </summary>
    public List<string> PassedValidations { get; set; } = new();

    /// <summary>
    /// List of failed validation names
    /// </summary>
    public List<string> FailedValidations { get; set; } = new();
}

/// <summary>
/// AI-generated recommendation with evidence
/// </summary>
public class EnhancedRecommendationDto
{
    /// <summary>
    /// Recommendation type: Approve, RequestResubmission, Reject
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// Brief summary of recommendation
    /// </summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>
    /// List of critical issues
    /// </summary>
    public List<IssueDto> CriticalIssues { get; set; } = new();

    /// <summary>
    /// List of high priority issues
    /// </summary>
    public List<IssueDto> HighPriorityIssues { get; set; } = new();

    /// <summary>
    /// List of medium priority issues
    /// </summary>
    public List<IssueDto> MediumPriorityIssues { get; set; } = new();

    /// <summary>
    /// List of passed validations
    /// </summary>
    public List<string> PassedValidations { get; set; } = new();

    /// <summary>
    /// Risk assessment: Low, Medium, High
    /// </summary>
    public string RiskAssessment { get; set; } = string.Empty;

    /// <summary>
    /// Recommended action for ASM
    /// </summary>
    public string RecommendedAction { get; set; } = string.Empty;
}

/// <summary>
/// Individual validation issue
/// </summary>
public class IssueDto
{
    /// <summary>
    /// Issue title
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Detailed description
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Expected value
    /// </summary>
    public string ExpectedValue { get; set; } = string.Empty;

    /// <summary>
    /// Actual value
    /// </summary>
    public string ActualValue { get; set; } = string.Empty;

    /// <summary>
    /// Impact on approval
    /// </summary>
    public string Impact { get; set; } = string.Empty;

    /// <summary>
    /// Suggested resolution
    /// </summary>
    public string SuggestedResolution { get; set; } = string.Empty;

    /// <summary>
    /// Severity level
    /// </summary>
    public string Severity { get; set; } = string.Empty;
}
